export const users = [
  {
    name: 'Fatass',
    intra_name: 'Fatass',
    intra_id: 1,
    experience: 0,
    wins: 0,
    losses: 8,
  },
  {
    name: 'Assfat',
    intra_name: 'Assfat',
    intra_id: 2,
    experience: 1,
    wins: 3,
    losses: 0,
  },
  {
    name: 'Shiteater',
    intra_name: 'Shiteater',
    intra_id: 3,
    experience: 2,
    wins: 5,
    losses: 0,
  },
  {
    name: 'fml',
    intra_name: 'fml',
    intra_id: 4,
    experience: 1,
    wins: 2,
    losses: 3,
  },
  {
    name: 'Quincy Promes',
    intra_name: 'Quincy Promes',
    intra_id: 5,
    experience: 10,
    wins: 10,
    losses: 0,
  },
  {
    name: 'Biggiedaggoe',
    intra_name: 'Biggiedaggoe',
    intra_id: 6,
    experience: 0,
    wins: 0,
    losses: 10,
  },
  {
    name: 'Bruh',
    intra_name: 'Bruh',
    intra_id: 7,
    experience: 2,
    wins: 1,
    losses: 4,
  },
  {
    name: 'Moffel',
    intra_name: 'Moffel',
    intra_id: 8,
    experience: 2,
    wins: 1,
    losses: 4,
  },
];
